### PR TITLE
fix: remove is_singular

### PR DESCRIPTION
**Pull request by im-adithya**
Passes `$post_id` to `getLightningClient` to avoid the use of `is_singular`

### CODE REVIEW

**Comment by bumi** [comment]
@Bobz-zg what do you think,does this make sense?

**Comment by Bobz-zg** [comment]
@bumi yes, this should work like this

**Comment by bumi** [comment]
@Bobz-zg thanks. so you're ok to merge this?

**Comment by Bobz-zg** [comment]
@bumi  Yes. I'm ok to merge this. Looks good, thanks @im-adithya for the fix.

**Pull request merged**
